### PR TITLE
add insertion_sort. tested

### PR DESCRIPTION
**Pull request by jwharrow**

### CODE REVIEW

**Comment by jwharrow** [comment]
@mattheweller finally figured out insertion sort. check it out if you want.

**Comment by mattheweller** [comment]
Nice! That's really awesome! Definitely a tricky one. I managed to get a working version based on the wiki page we were looking at: https://github.com/mattheweller/phase-0-tracks/blob/master/ruby/problem_solving_methods.rb

**Comment by jwharrow** [comment]
@mattheweller Yeah, that's a cleaner solution. I let myself get hung up on making it work with the insert method.

**Comment by mattheweller** [comment]
@jwharrow, thanks! I think the takeaway for me is to watch out for array methods that return nil when they overrun the length of their array, by either looking for nil as you did, or decrement like I did and stopping when your index variable reaches 0.

**Pull request merged**
